MODEL:
  TYPE: nas
  NUM_CLASSES: 100
NAS:
  GENOTYPE: custom
  WIDTH: 36
  DEPTH: 20
  AUX: True
  DROP_PROB: 0.2
  AUX_WEIGHT: 0.4
OPTIM:
  BASE_LR: 0.025
  LR_POLICY: cos
  MAX_EPOCH: 600
  MOMENTUM: 0.9
  NESTEROV: False
  WEIGHT_DECAY: 0.0005
TRAIN:
  DATASET: cifar100
  SPLIT: train
  BATCH_SIZE: 96
  IM_SIZE: 32
  CHECKPOINT_PERIOD: 10
  EVAL_PERIOD: 1
  CUTOUT: True
  CUTOUT_LENGTH: 16
TEST:
  DATASET: cifar100
  SPLIT: test
  BATCH_SIZE: 96
  IM_SIZE: 32
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 8
CUDNN:
  BENCHMARK: True
OUT_DIR: .
