MODEL:
  TYPE: nas_search
  NUM_CLASSES: 4
NAS:
  WIDTH: 16
  DEPTH: 8
OPTIM:
  BASE_LR: 0.0125
  LR_POLICY: cos
  MAX_EPOCH: 50
  MOMENTUM: 0.9
  NESTEROV: False
  WEIGHT_DECAY: 0.0003
  ITER_LR: False
  ARCH_BASE_LR: 0.0003
  ARCH_WEIGHT_DECAY: 0.001
  ARCH_EPOCH: 1.0
TRAIN:
  DATASET: cifar100
  SPLIT: train
  BATCH_SIZE: 32
  IM_SIZE: 32
  EVAL_PERIOD: 1
  PORTION: 0.5
TEST:
  BATCH_SIZE: 32
  IM_SIZE: 32
TASK: rot
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 8
CUDNN:
  BENCHMARK: True
OUT_DIR: .
